#!/bin/bash

curl -s https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly

sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
sudo apt update
sudo apt install -y gcc-arm-embedded

rustup install nightly
rustup default nightly
rustup target add thumbv6m-none-eabi

rustup component add clippy-preview
rustup component add rust-src

cargo +nightly install racer
cargo +nightly install cargo-outdated
cargo +nightly install cargo-edit
cargo +nightly install cargo-modules

cargo install svd2rust  --git https://github.com/rust-embedded/svd2rust.git
