#!/bin/bash

# General stuff.

sudo apt-get install \
	apt-transport-https \
	ca-certificates \
	curl \
	software-properties-common -y

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

sudo add-apt-repository ppa:kelleyk/emacs

sudo apt-get update

sudo apt-get install -y \
     tmux vim git git-gui gitk i3 i3blocks zsh curl cmake emacs26 freecad dropbear-bin jq docker-ce parallel htop pulseaudio-module-bluetooth blueman pavucontrol xfce4-settings gnuplot git-gui microcom gdb-multiarch \
     python-pip python3-pip python-protobuf \
     openjdk-8-jdk openjdk-11-jdk \
     ledger hledger hledger-ui hledger-web python-ledger \
     nfs-kernel-server nfs-common

pip install s-tui --user

# This messes with embedded work.
systemctl stop ModemManager
systemctl disable ModemManager.service

# Trying this out for now as well.
sudo rm /lib/udev/rules.d/*mtp*
