# ~/.tmuxinator/cloud.yml

name: fk-app
root: ~/fieldkit/app

startup_window: 1
startup_pane: 1

windows:
  - shell:
  - shells:
      layout: main-horizontal
      panes:
        - shell:
          - clear
        - shell:
          - clear
