
import = [ "alabaster.yaml" ]
import = [ "argonaut.yaml" ]
import = [ "atom_one_light.yaml" ]
import = [ "ayu_dark.yaml" ]
import = [ "ayu_light.yaml" ]
import = [ "baitong.yaml" ]
import = [ "base16_default_dark.yaml" ]
import = [ "blood_moon.yaml" ]
import = [ "bluish.yaml" ]
import = [ "breeze.yaml" ]
import = [ "campbell.yaml" ]
import = [ "carbonfox.yaml" ]
import = [ "catppuccin.yaml" ]
import = [ "challenger_deep.yaml" ]
import = [ "citylights.yaml" ]
import = [ "Cobalt2.yaml" ]
import = [ "cyber_punk_neon.yaml" ]
import = [ "darcula.yaml" ]
import = [ "dark_pastels.yaml" ]
import = [ "deep_space.yaml" ]
import = [ "doom_one.yaml" ]
import = [ "dracula.yaml" ]
import = [ "everforest_dark.yaml" ]
import = [ "everforest_light.yaml" ]
import = [ "falcon.yaml" ]
import = [ "flat_remix.yaml" ]
import = [ "flexoki.yaml" ]
import = [ "github_dark_colorblind.yaml" ]
import = [ "github_dark_default.yaml" ]
import = [ "github_dark.yaml" ]
import = [ "github_dimmed.yaml" ]
import = [ "github_light_colorblind.yaml" ]
import = [ "github_light_default.yaml" ]
import = [ "github_light.yaml" ]
import = [ "gnome_terminal.yaml" ]
import = [ "gotham.yaml" ]
import = [ "gruvbox_dark.yaml" ]
import = [ "gruvbox_light.yaml" ]
import = [ "gruvbox_material_medium_dark.yaml" ]
import = [ "gruvbox_material_medium_light.yaml" ]
import = [ "hardhacker.yaml" ]
import = [ "high_contrast.yaml" ]
import = [ "horizon-dark.yaml" ]
import = [ "hyper.yaml" ]
import = [ "inferno.yaml" ]
import = [ "iterm.yaml" ]
import = [ "kanagawa_dragon.yaml" ]
import = [ "kanagawa_wave.yaml" ]
import = [ "konsole_linux.yaml" ]
import = [ "low_contrast.yaml" ]
import = [ "Mariana.yaml" ]
import = [ "marine_dark.yaml" ]
import = [ "material_theme_mod.yaml" ]
import = [ "material_theme.yaml" ]
import = [ "midnight-haze.yaml" ]
import = [ "monokai_charcoal.yaml" ]
import = [ "monokai_pro.yaml" ]
import = [ "moonlight_ii_vscode.yaml" ]
import = [ "msx.yaml" ]
import = [ "nightfox.yaml" ]
import = [ "night_owlish_light.yaml" ]
import = [ "noctis-lux.yaml" ]
import = [ "nordic.yaml" ]
import = [ "nord_light.yaml" ]
import = [ "nord.yaml" ]
import = [ "oceanic_next.yaml" ]
import = [ "omni.yaml" ]
import = [ "one_dark.yaml" ]
import = [ "palenight.yaml" ]
import = [ "papercolor_dark.yaml" ]
import = [ "papercolor_light.yaml" ]
import = [ "papertheme.yaml" ]
import = [ "pencil_dark.yaml" ]
import = [ "pencil_light.yaml" ]
import = [ "rainbow.yaml" ]
import = [ "remedy_dark.yaml" ]
import = [ "rose-pine-dawn.yaml" ]
import = [ "rose-pine-moon.yaml" ]
import = [ "rose-pine.yaml" ]
import = [ "seashells.yaml" ]
import = [ "smoooooth.yaml" ]
import = [ "snazzy.yaml" ]
import = [ "solarized_dark.yaml" ]
import = [ "solarized_light.yaml" ]
import = [ "taerminal.yaml" ]
import = [ "tango_dark.yaml" ]
import = [ "tender.yaml" ]
import = [ "terminal_app.yaml" ]
import = [ "thelovelace.yaml" ]
import = [ "tokyo-night-storm.yaml" ]
import = [ "tokyo-night.yaml" ]
import = [ "tomorrow_night_bright.yaml" ]
import = [ "tomorrow_night.yaml" ]
import = [ "ubuntu.yaml" ]
import = [ "wombat.yaml" ]
import = [ "xterm.yaml" ]
import = [ "zenburn.yaml" ]

